### PR TITLE
Ticket 3

### PR DESCRIPTION
**Pull request by Nick-T-Hansen**
# Description

Added controllers and tests for ticket 3, Payment Type

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions for Change Made

git checkout master
git fetch --all
git checkout ticket-3
add test data shared in slack
run tests in text explorer

# Checklist:

- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [ X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by loetek — COMMENTED** [review]
All PostMan and test conditions passed.

**Review by loetek — APPROVED** [review]
Approved via Postman and Tests

**Review by AnupamaGarg — APPROVED** [review]
Test Passed

**Review by MissPeperr — APPROVED** [review]
👍 Seal of approval! 👍

**Pull request merged**
